smpl_bone_list = [
    "pelvis",
    "left_hip",
    "right_hip",
    "spine1",
    "left_knee",
    "right_knee",
    "spine2",
    "left_ankle",
    "right_ankle",
    "spine3",
    "left_foot",
    "right_foot",
    "neck",
    "left_collar",
    "right_collar",
    "head",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_hand",
    "right_hand"
]

# SMPL 관절 이름 (순서대로)
smpl_joint_names = [
    "pelvis", 
    "left_hip", 
    "right_hip", 
    "spine1", 
    "left_knee", 
    "right_knee", 
    "spine2", 
    "left_ankle", 
    "right_ankle", 
    "left_shoulder", 
    "right_shoulder", 
    "spine3", 
    "left_elbow", 
    "right_elbow", 
    "neck", 
    "left_wrist", 
    "right_wrist", 
    "head", 
    "left_hand", 
    "right_hand", 
    "left_foot", 
    "right_foot", 
    "left_toe", 
    "right_toe"
]

# MIXAMO to SMPL 관절 매핑 ( MIXAMO -> SMPL )
mixamo_to_smpl_map = {
    "mixamorig:Hips": "pelvis",
    "mixamorig:LeftUpLeg": "left_hip",
    "mixamorig:RightUpLeg": "right_hip",
    "mixamorig:Spine": "spine1",
    "mixamorig:LeftLeg": "left_knee",
    "mixamorig:RightLeg": "right_knee",
    "mixamorig:Spine1": "spine2",
    "mixamorig:LeftFoot": "left_ankle",
    "mixamorig:RightFoot": "right_ankle",
    "mixamorig:Spine2": "spine3",
    "mixamorig:LeftToeBase": "left_foot",
    "mixamorig:RightToeBase": "right_foot",
    "mixamorig:Neck": "neck",
    "mixamorig:LeftShoulder": "left_collar",
    "mixamorig:RightShoulder": "right_collar",
    "mixamorig:Head": "head",
    "mixamorig:LeftArm": "left_shoulder",
    "mixamorig:RightArm": "right_shoulder",
    "mixamorig:LeftForeArm": "left_elbow",
    "mixamorig:RightForeArm": "right_elbow",
    "mixamorig:LeftHand": "left_wrist",
    "mixamorig:RightHand": "right_wrist",
    "mixamorig:LeftHandMiddle1": "left_hand",
    "mixamorig:RightHandMiddle1": "right_hand"
}

# SMPL to MIXAMO 관절 매핑 (SMPL -> MIXAMO)
smpl_to_mixamo_map = {
    "pelvis": "mixamorig:Hips",
    "left_hip": "mixamorig:LeftUpLeg",
    "right_hip": "mixamorig:RightUpLeg",
    "spine1": "mixamorig:Spine",
    "left_knee": "mixamorig:LeftLeg",
    "right_knee": "mixamorig:RightLeg",
    "spine2": "mixamorig:Spine1",
    "left_ankle": "mixamorig:LeftFoot",
    "right_ankle": "mixamorig:RightFoot",
    "spine3": "mixamorig:Spine2",
    "left_foot": "mixamorig:LeftToeBase",
    "right_foot": "mixamorig:RightToeBase",
    "neck": "mixamorig:Neck",
    "left_collar": "mixamorig:LeftShoulder",
    "right_collar": "mixamorig:RightShoulder",
    "head": "mixamorig:Head",
    "left_shoulder": "mixamorig:LeftArm",
    "right_shoulder": "mixamorig:RightArm",
    "left_elbow": "mixamorig:LeftForeArm",
    "right_elbow": "mixamorig:RightForeArm",
    "left_wrist": "mixamorig:LeftHand",
    "right_wrist": "mixamorig:RightHand",
}
